// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiP9F88BDSjXL-WzKqpSmlqo6nHB4OHkM',
    appId: '1:1008198517398:web:d3d06a26917cde2238f8b7',
    messagingSenderId: '1008198517398',
    projectId: 'chss-noon-meal',
    authDomain: 'chss-noon-meal.firebaseapp.com',
    storageBucket: 'chss-noon-meal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActmIB1W4rP5Y4kjYRaT5ny7KGLQTNNP0',
    appId: '1:1008198517398:android:e95b454955b4df1238f8b7',
    messagingSenderId: '1008198517398',
    projectId: 'chss-noon-meal',
    storageBucket: 'chss-noon-meal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VZlmB_cxxjgqOiqUCYcwvBh7H6bFuB8',
    appId: '1:1008198517398:ios:871f898e77d7f99738f8b7',
    messagingSenderId: '1008198517398',
    projectId: 'chss-noon-meal',
    storageBucket: 'chss-noon-meal.appspot.com',
    iosBundleId: 'in.zedone.chssNoonMeal',
  );

}