import 'package:flutter/material.dart';

class AppColors {
  static const Color mainColor = Color(0xff2A3990);
  static const Color iconColor1 = Color(0xFFffd28d);
  static const Color iconColor2 = Color(0xFFfcab88);
  static const Color paraColor = Color(0xFF8f837f);
  static const Color buttonBackgroundColor = Color(0xFFf7f6f6);
  static const Color signColor = Color(0xFFa9a29f);
  static const Color titleColor = Color(0xFF5c524f);
  static const Color mainBlackColor = Color(0xFF332d2b);
  static const Color yellowColor = Color(0xffF8F5AA);
  static const Color yellowColorDark = Color(0xFFffb379);
  static const Color incentiveColor = Color(0xff95f4d4);
  static const Color orangeYellow = Color(0xfffcae3d);
  static const Color targetSectionColor = Color(0xfff56472);
  static const Color colorPrimary = Color(0xffE4282D);
  static const Color statusBarColor = Color(0xffE4282D);
  static const Color dashboardLeadTileBG = Color(0xffff944d);

  static const Color cyan = Color(0xff8CDADF);
  static const Color green = Color(0xff2EB661);
  static const Color textColor = Color(0xffa1a1a1);
  static const Color lightGrey = Color(0xfff1f1f1);
  static const Color formIconCircleColor = Color(0xffaeaaa8);
  static const Color keyboard_BG = Color(0xffF3F3F3);
  static const Color textFieldBg = Color(0xfff5f5f5);
  static const Color white = Color(0xffffffff);
  static const Color backgroundColor = Color(0xffF3F8FE);
  static const Color black = Color(0xff000000);
  static const Color targetValueBoxBg = Color(0xffECF5FF);
  static const Color targetAchievedTextColor = Color(0xff00C399);
  static const Color visitOverviewBg = Color(0xffFDEEEE);
  static const Color blackLight = Color(0xff3A3A3A);
  static const Color dividerColor = Color(0xffE2ECF8);
  static const Color darkGrey = Color(0xff1C1E26);
  static const Color title_color = Color(0xff767B85);
  static const Color punchoutColor = Color(0xffC1C5CC);
  static const Color orderAddanotherbg = Color(0xffF3F8FE);
  static const Color orderAddcommentbg = Color(0xffE2ECF8);
  static const Color transparent = Color(0x00ffffff);
  static const Color buttoncustomcolorblue = Color(0xff007ECF);
  static const Color pendingbg = Color(0xffFEE9DB);
  static const Color pendingtext = Color(0xffF8934A);
  static const Color schemebg = Color(0xffFFECEF);
  static const Color drawerItemColor = Color(0xffD9D9D9);
  static const Color selectedTabItemColor = Color(0xffFDFBC4);
  static const Color cashPaymentColor = Color(0xff08BC4A);
  static const Color chequePaymentColor = Color(0xffEC368C);
  static const Color onlinePaymentColor = Color(0xffF48A0E);
  static const Color cardPaymentColor = Color(0xff17ADCE);
  static const Color upiPaymentColor = Color(0xff653BBE);
  static const Color fieldLineColor = Color(0xffDCDFE5);
  static const Color dottedLineColor = Color(0xff82B5EF);
  static const Color dottedBoxBgColor = Color(0xffF1F9FF);
  static const Color checkTickRoundIconColor = Color(0xff00C29F);
  static const Color checkTickRoundedRectangleBgColor = Color(0xff17CB84);
  static const Color roundedRectangularBorderColor = Color(0xff292D32);
  static const Color commentTextColor = Color(0xff7B7B7B);
  static const Color invoicecard = Color(0xfff7fff2);
  static const Color commitmentstatusbg = Color(0xffFFCDD2); //#FFCDD2
  static const Color commitmentbuttonbg = Color(0xffD6E6F8); //#FFCDD2
  static const Color commitmentbuttontext = Color(0xff0933C9); //#FFCDD2
  static const Color noButtonBgColor = Color(0xffE7EBEF);
  static const Color greyColor = Color(0xffA1A1A1);
  static const Color greyBoxBorderColor = Color(0xffE4E9EE);
  static const Color lightYellowColor = Color(0xffFAEDAA);
  static const Color ageingFilterTextFieldColor = Color(0xffF1F5FA);
  static const Color greenButtonBorderColor = Color(0xff15B374);
  static const Color rejectedTextColor = Color(0xffED273F);
  static const Color textFiledOutlineBorderColor = Color(0xff70B1E1);

  static const Color bgaddsurevyw = Color(0xffFCFEFF);
  static const Color lightwhite = Color(0xffF9FCFF);
  static const Color approvedtext = Color(0xff03C66B); //background: #03C66B33;

  static const Color mrnDetailBg = Color(0xffE6F1FF);
  static const Color idColor = Color(0xffE2F282);
  static const Color targetIndicatorDisabledColor = Color(0xffBFCEE1);
  static const Color fabDisabledColor = Color(0xff1D213C);
  static const Color dividerLineColor = Color(0xffDCE3F2);
  static const Color commitmentDatabg = Color(0xffEFF5FC);
  static const Color commitmentCloseBtnBg = Color(0xffE75E87);
  static const Color denominationBoxBg = Color(0xffFFEAF7);
  ///notification
  static const Color notificationLight = Color(0xffF6F5D6);
  static const Color notificationDark = Color(0xffD79547);
  static const Color notificationIconCircle= Color(0xffEBF0F9);
  static const Color notificationIconCircleBoarder = Color(0xffD2DDF3);
  static const Color notificationBell = Color(0xff012C79);
  static const Color notificationBlue = Color(0xff046AE2);
  static const Color notificationGrey = Color(0xff787878);

  static const Color completelight = Color(0xffD2F7D6);
  static const Color completedark = Color(0xff07BF69);
  static const Color convertlight= Color(0xffF3E2FE);
  static const Color convertdark = Color(0xff5807BF);
  static const Color wiplight = Color(0xffFEE9DB);
  static const Color wipdark = Color(0xffF8934A);
  static const Color rejectlight = Color(0xffFCECEE);
  static const Color rejectdark = Color(0xffED273F);
  static const Color app_color = Color(0xff285da3);
  static const Color headerColor= Color(0xff78398d);
}
